services:
  website:
    image: ${CUSTOM_IMAGE:-svasamm/lucoze-website}:${CUSTOM_TAG:-latest}
    pull_policy: ${PULL_POLICY:-always}
    ports:
      - mode: ingress
        host_ip: ${AGENT_PRIVATE_IP}
        target: 80
        published: "${BENCH_PORT}"
        protocol: tcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
