#!/usr/bin/env python3
"""Regenerate self-hosted, subsetted webfonts + src/styles/fonts.css.

Why this exists: the render-blocking fonts.googleapis.com stylesheet was the
dominant LCP bottleneck on throttled mobile (SEO audit 2026-07-20). We self-host
instead, subsetting each face to the exact characters the site renders.

Run from the repo root after changing font families/weights in FONT_CSS_URL, or
after adding UI copy in a new script (re-check UNICODES still covers it):

    pip install fonttools brotli
    python3 scripts/build-fonts.py

Then rebuild the site. Indic scripts are intentionally excluded — these are Latin
faces that never covered Devanagari/Bengali/Odia, so that text falls back to
system fonts exactly as it did with Google Fonts. latin-ext is kept because the
rupee sign U+20B9 (in U+20AD-20C0) appears across pricing/billing/compare copy.
"""

import os
import re
import subprocess
import urllib.request
from pathlib import Path

from fontTools.ttLib import TTFont

# The exact families/weights the design uses (matches the old Google Fonts URL).
FONT_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Manrope:wght@400;500;600;700;800"
    "&family=Inter+Tight:wght@400;500;600;700"
    "&family=JetBrains+Mono:wght@400;500;600"
    "&family=Fraunces:ital,opsz,wght@0,9..144,400..600;1,9..144,400..600"
    "&display=swap"
)
# A browser UA is required or Google serves legacy TTF instead of woff2.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
# Basic Latin + Latin-1 + Latin Ext-A, plus the exact punctuation, arrows,
# symbols and currency (₹, €, ·, ©, ×, ✓, →) the site actually renders.
UNICODES = (
    "U+0020-007E,U+00A0-00FF,U+0100-017F,U+2013,U+2014,U+2018,U+2019,"
    "U+201C,U+201D,U+2026,U+2039,U+203A,U+2122,U+2190-2193,U+2212,U+2215,"
    "U+2713,U+2714,U+00D7,U+00B7,U+00A9,U+20AC,U+20B9"
)
FONTS_DIR = Path("public/fonts")
CSS_OUT = Path("src/styles/fonts.css")

HEADER = """/* Self-hosted, subsetted webfonts (latin + latin-ext).
 * GENERATED by scripts/build-fonts.py — do not edit by hand.
 * Replaces the render-blocking fonts.googleapis.com stylesheet, which wasted
 * ~1s on throttled mobile via the googleapis->gstatic round trip (SEO audit
 * 2026-07-20). Each face is subset to the exact characters the site renders.
 * Indic scripts absent by design — these Latin faces never had them, so
 * Hindi/Bengali/Odia falls back to system fonts. latin-ext kept: rupee U+20B9
 * (U+20AD-20C0) is used across pricing/billing/compare. */
"""


def fetch_css() -> str:
    req = urllib.request.Request(FONT_CSS_URL, headers={"User-Agent": UA})
    return urllib.request.urlopen(req).read().decode()


def main() -> None:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    for f in FONTS_DIR.glob("*.woff2"):
        f.unlink()

    css = fetch_css()
    faces = re.findall(r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", css, re.S)
    blocks = [HEADER]
    total = 0
    for subset, body in faces:
        fam = re.search(r"font-family: '([^']+)'", body).group(1)
        weight = re.search(r"font-weight: ([^;]+);", body).group(1).strip()
        style = re.search(r"font-style: ([^;]+);", body).group(1).strip()
        urange = re.search(r"unicode-range: ([^;]+);", body).group(1).strip()
        src_url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)

        slug = fam.lower().replace(" ", "-")
        wtag = weight.replace(" ", "-")  # variable faces give "400 600"
        name = f"{slug}-{wtag}{'-italic' if style == 'italic' else ''}-{subset}.woff2"
        dst = FONTS_DIR / name

        raw = urllib.request.urlopen(
            urllib.request.Request(src_url, headers={"User-Agent": UA})
        ).read()
        tmp = FONTS_DIR / f".{name}.src"
        tmp.write_bytes(raw)
        subprocess.run(
            ["pyftsubset", str(tmp), f"--output-file={dst}", f"--unicodes={UNICODES}",
             "--flavor=woff2", "--layout-features=kern,liga,calt",
             "--no-hinting", "--desubroutinize", "--drop-tables+=DSIG"],
            check=True, capture_output=True,
        )
        tmp.unlink()

        # A face left with no glyphs in our range (e.g. a subset the site never
        # hits) is dropped rather than shipped empty.
        if len(TTFont(dst).getBestCmap()) <= 1:
            dst.unlink()
            continue

        total += dst.stat().st_size
        blocks.append(
            f'/* {subset} */\n@font-face {{\n'
            f'\tfont-family: "{fam}";\n\tfont-style: {style};\n'
            f'\tfont-weight: {weight};\n\tfont-display: swap;\n'
            f'\tsrc: url("/fonts/{name}") format("woff2");\n'
            f'\tunicode-range: {urange};\n}}'
        )

    CSS_OUT.write_text("\n\n".join(blocks) + "\n")
    print(f"{len(blocks) - 1} faces, {total / 1024:.0f} KB total -> {CSS_OUT}")


if __name__ == "__main__":
    os.chdir(Path(__file__).resolve().parent.parent)
    main()
