name: Tests

on:
  push:
    branches: [main, develop, uat]
  pull_request:

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - name: Run tests
        run: npm test

      - name: Run coverage
        run: npm run test:coverage
